Starter Project
TheComposers/LetsGitHubSearch pull request #1
Opened 2022-11-27 08:22 UTC by dy-kim

- 실습 시작을 위한 프로젝트
- Vanilla SwiftUI로 구현
- Dummy repositories를 검색하는 아주 간단한 앱

2022-11-27 08:22 UTC, dy-kim commented
@bbvch13531 리뷰 해주시면 `Squash and merge` 할게요!

2022-11-27 08:27 UTC, dy-kim commented on starter/GitHubSearch/Repository/RepoSearchClient.swift
> +      let url = URL(string: "https://api.github.com/search/repositories?q=\(keyword)")!
@bbvch13531 이 부분 force unwrapping으로 처리하고 APIError 타입 없앴는데 어떠신가요? 에러 가능성도 없고 더 간결한 것 같아요~

2022-11-27 09:02 UTC, bbvch13531 requested changes

2022-11-27 09:02 UTC, bbvch13531 commented on starter/GitHubSearch/Repository/RepoSearch.swift
> +    //   case .keywordChanged:
```suggestion
    //   case let .keywordChanged(keyword):
```

2022-11-27 09:02 UTC, bbvch13531 commented on starter/GitHubSearch/Repository/RepoSearch.swift
> +    // keywordChanged, searchButtonTapped 액션 추가하기
`searchButtonTapped`대신에 `search`를 제안합니다.
`searchButtonTapped`라는 action은 UI의 구현에 의존하고 있기 때문에 
실제 동작은 search라는 액션이지만 buttonTapped에 해당하는 UI가 바뀌면 불필요하게 바뀌게 됩니다.
reducer의 action은 UI의 구현과는 관련이 없도록 추상화 레이어를 분리하는 쪽이 더 좋다고 생각합니다.

2022-11-27 09:02 UTC, bbvch13531 commented on starter/GitHubSearch/Repository/RepoSearchClient.swift
> +}
```swift
func sampleSearchRequest(keyword: String, send: Send<RepoSearch.Action>) async throws {
  guard let url = URL(string: "https://api.github.com/search/repositories?q=\(keyword)") else {
    await send(RepoSearch.Action.dataLoaded(.failure(APIError.invalidUrlError)))
    return
  }
  let (data, _) = try await URLSession.shared.data(from: url)
  let result = await TaskResult { try JSONDecoder().decode(RepositoryModel.self, from: data) }

  await send(RepoSearch.Action.dataLoaded(result))
}
```

Workshop2의 중간단계에서 사용할 simpleSearchRequest func 추가가 필요합니다.
workshop하는 도중 이 코드를 직접 타이핑하게 하기 보다는
중간단계에서만 임시로 사용하고 곧 SearchClient를 사용하는 코드로 바꾸기 때문에 
미리 함수로 제공해서 가져다 쓰도록 하는 것이 시간적인 측면에서 좋을 것 같습니다.

2022-11-27 09:02 UTC, bbvch13531 commented on starter/GitHubSearchTests/GitHubSearchTests.swift
> +  }
```suggestion
  func test_user_has_repoSearchResults_when_search() async {
    // Arrange
    // TestStore를 생성합니다.

    // Act & Assert
    // store.send(.keywordChanged("Swift")) 할 때 
    // send.keyword가 "Swift"인지 테스트합니다.
  }
```

테스트케이스를 유저시나리오에 맞춰서 수정하는건 어떨까요?

그리고 테스트에도 간단한 주석을 추가하면 좋을 것 같습니다.

2022-11-27 09:02 UTC, bbvch13531 commented on .gitignore
> +
.gitignore 에 불필요한 항목들이 많습니다.
주석의 설명을 읽어보시면 아시겠지만, 다음 항목들 외에는 전부 불필요한 파일입니다.
제거 부탁드립니다.
```
xcuserdata/
.build/
.DS_Store
```

2022-11-27 09:02 UTC, bbvch13531 commented on starter/GitHubSearchTests/GitHubSearchTests.swift
> +final class GitHubSearchTests: XCTestCase {
이 테스트는 Repository 라는 모듈에 대한 테스트이기 때문에 이름을 `GitHubSearchTests`에서 `RepositoryTests`로 수정하는 것이 올바를 것 같습니다.

2022-11-28 03:40 UTC, dy-kim commented on starter/GitHubSearch/Repository/RepoSearchClient.swift
> +}
이 코드는 starter에 추가한다면 주석으로 들어가야하니 깃헙에 올라가는 코드에 올리기 보다는, 워크샵 시작하기 전에 주석으로 살짝 붙여 놓으면 될 것 같아요.

2022-11-28 06:02 UTC, bbvch13531 requested changes

2022-11-28 06:02 UTC, bbvch13531 commented on starter/GitHubSearchTests/RepositoryTests.swift
> +  }
```suggestion
  
  func test_keyword_changed_when_user_typed() async {
      // Arrange
      // TestStore를 생성합니다.
      
      // Act & Assert
      // 유저가 "Swift"를 입력했을 때, state.keyword가 "Swift"인지 테스트합니다.
  }
  
  func test_user_has_repoSearchResults_when_search() async {
    // Arrange
    // TestStore를 생성합니다.

    // Act & Assert
    // 검색을 했을 때, 예상하는 검색 결과가 나오는지를 테스트합니다.
  }
```

Markdown 문법을 쓰지 않는 쪽이 좋아보입니다. 

keyword 입력에 대한 테스트와 검색에 대한 테스트로 테스트케이스를 나눠서 작성하는게 좋을 것 같습니다.
두번째 테스트케이스에서 TestStore의 keyword="Swift"를 InitialState로 생성하는건 어떨까요

KeywordChanged에 대한 Action과 search에 대한 Action을 분리해서 자연스럽게 테스트할 수 있을 것 같습니다.

2022-11-28 06:29 UTC, bbvch13531 approved these changes
LGTM 👍

2022-11-28 06:33 UTC, merged